name: Update RSS Clusters

on:
  schedule:
    # chạy 15 phút/lần
    - cron: "*/15 * * * *"
  workflow_dispatch:   # run → “Actions ▸ Run workflow” thủ công

jobs:
  update:
    runs-on: ubuntu-latest

    env:                      # ⬅️  Đổ secret vào biến môi trường cho index.js
      BASE_URL_LOCAL: 'http://ziplyfiber9232.tplinkdns.com:8011'
      API_USERNAME:    ${{ secrets.API_USERNAME }}
      API_PASSWORD:    ${{ secrets.API_PASSWORD }}
      PROXY_LOCAL_URL: ${{ secrets.PROXY_LOCAL_URL }}
      RSS_KEY_SECRET:  ${{ secrets.RSS_KEY_SECRET }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0            # cần full history để commit đè

      - name: Setup Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm               # cache ~/.npm

      - name: Install deps
        run: |
          npm install axios rss-parser fast-xml-parser https-proxy-agent

      - name: Run RSS merger
        run: node index.js

      - name: Commit & push if changed
        run: |
          if git status --porcelain | grep -q 'cumdaura.*\\.xml'; then
            git config user.name  "github-actions[bot]"
            git config user.email "github-actions[bot]@users.noreply.github.com"
            git add cumdaura*.xml
            git commit -m "🔄 update RSS clusters [skip ci]"
            git push
          else
            echo "No change — skip commit."
          fi
