name: Build & Deploy RSS to gh-pages 1

on:
  schedule:
    - cron: "*/6 * * * *"
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    env:
        BASE_URL_LOCAL:  ${{ secrets.BASE_URL_LOCAL }}
        API_USERNAME:    ${{ secrets.API_USERNAME }}
        API_PASSWORD:    ${{ secrets.API_PASSWORD }}
        PROXY_LOCAL_URL: ${{ secrets.PROXY_LOCAL_URL }}
        RSS_KEY_SECRET:  ${{ secrets.RSS_KEY_SECRET }}
    steps:
      - name: Checkout main branch
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Run script
        run: node index.js

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./
          publish_branch: gh-pages
          commit_message: "🚀 Update Nitter RSS"
